import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('es');

  const translations: Record<Language, Record<string, string>> = {
    es: {
      // Header
      'header.name': 'José Rodrigo Escutia Ríos',
      'header.downloadCV': 'Descargar CV',
      'header.downloadCVShort': 'CV',
      
      // Sidebar
      'sidebar.dashboard': 'Dashboard',
      'sidebar.appium': 'Appium',
      'sidebar.cypress': 'Cypress',
      'sidebar.karatebdd': 'Karate BDD',
      'sidebar.mentoria': 'Mentoría',
      'sidebar.playwright': 'Playwright',
      'sidebar.selenium': 'Selenium',
      
      // Languages
      'lang.spanish': 'Español',
      'lang.english': 'English',
      
      // Appium
      'appium.title': 'Appium',
      'appium.subtitle': 'Automatización móvil profesional con Appium y Java',
      'appium.tab.github': 'Descarga desde GitHub',
      'appium.tab.guide': 'Guía de Uso',
      'appium.framework': 'Framework de Automatización',
      'appium.preReq.title': 'Requisitos previos',
      'appium.preReq.java': 'Java JDK 17 o superior',
      'appium.preReq.maven': 'Maven 3.8 o superior',
      'appium.preReq.node': 'Node.js y npm',
      'appium.preReq.android': 'Android SDK configurado',
      'appium.preReq.device': 'Dispositivo Android con depuración USB activada',
      
      // GitHub steps
      'appium.step1.title': 'Clonar el repositorio',
      'appium.step1.desc': 'Abre tu terminal y ejecuta el siguiente comando para clonar el proyecto:',
      'appium.step2.title': 'Verificar requisitos previos',
      'appium.step2.desc': 'Asegúrate de tener instalado Java JDK 17+, Maven 3.8+, Node.js y Appium:',
      'appium.step3.title': 'Instalar Appium y drivers',
      'appium.step3.desc': 'Si no tienes Appium instalado, ejecuta:',
      'appium.step4.title': 'Configurar Android SDK',
      'appium.step4.desc': 'Configura la variable de entorno ANDROID_HOME (Windows PowerShell):',
      'appium.step5.title': 'Instalar dependencias del proyecto',
      'appium.step5.desc': 'Instala todas las dependencias de Maven:',
      'appium.step6.title': 'Configurar dispositivo Android',
      'appium.step6.desc': 'Edita el archivo config.properties con los datos de tu dispositivo:',
      'appium.step7.title': 'Iniciar Appium Server',
      'appium.step7.desc': 'En una terminal aparte, inicia el servidor de Appium:',
      'appium.step8.title': 'Ejecutar pruebas',
      'appium.step8.desc': 'Conecta tu dispositivo Android y ejecuta las pruebas:',
      
      // Guide steps
      'appium.guide.intro.title': 'Crear un nuevo test de búsqueda en Google',
      'appium.guide.intro.desc': 'Esta guía te mostrará cómo crear un test completo para buscar la palabra "Automatización" en Google Chrome usando el patrón Page Object Model con Cucumber BDD.',
      'appium.guide1.title': 'Crear el archivo Feature',
      'appium.guide1.desc': 'Crea un nuevo archivo en src/test/resources/features/busqueda_automatizacion.feature:',
      'appium.guide2.title': 'Crear el Page Object (GoogleSearchPage.java)',
      'appium.guide2.desc': 'Crea src/main/java/com/mobile/automation/pages/GoogleSearchPage.java:',
      'appium.guide3.title': 'Crear Step Definitions (BusquedaAutomatizacionSteps.java)',
      'appium.guide3.desc': 'Crea src/test/java/com/mobile/automation/stepdefinitions/BusquedaAutomatizacionSteps.java:',
      'appium.guide4.title': 'Actualizar TestRunner.java (si es necesario)',
      'appium.guide4.desc': 'Verifica que tu TestRunner incluya el nuevo feature:',
      'appium.guide5.title': 'Configurar el dispositivo',
      'appium.guide5.desc': 'Obtén el ID de tu dispositivo y actualiza config.properties:',
      'appium.guide6.title': 'Iniciar Appium Server',
      'appium.guide6.desc': 'Abre una terminal y ejecuta Appium:',
      'appium.guide7.title': 'Ejecutar el test',
      'appium.guide7.desc': 'Ejecuta el nuevo test desde otra terminal:',
      'appium.guide8.title': 'Ver el reporte',
      'appium.guide8.desc': 'Una vez completada la ejecución, abre el reporte HTML:',
      
      // Tips
      'appium.tips.title': 'Tips adicionales',
      'appium.tips.locators': 'Locators:',
      'appium.tips.locators.desc': 'Usa Appium Inspector para identificar elementos correctamente',
      'appium.tips.waits': 'Esperas:',
      'appium.tips.waits.desc': 'Implementa esperas explícitas con',
      'appium.tips.tags': 'Tags:',
      'appium.tips.tags.desc': 'Usa tags como @smoke, @regression para organizar tus tests',
      'appium.tips.screenshots': 'Screenshots:',
      'appium.tips.screenshots.desc': 'Los errores capturan automáticamente screenshots',
      'appium.tips.reports': 'Reportes:',
      'appium.tips.reports.desc': 'Revisa el reporte HTML generado con ExtentReports para análisis detallado',
      
      // General
      'appium.step': 'Paso',
      'appium.copy': 'Copiar',
      'appium.copied': 'Copiado',
      
      // Cypress
      'cypress.title': 'Cypress',
      'cypress.subtitle': 'Automatización E2E con Cypress + TypeScript + Page Object Model + Reportes Word',
      'cypress.tab.github': 'Descarga desde GitHub',
      'cypress.tab.guide': 'Guía de Uso',
      'cypress.framework': 'Framework de Automatización',
      'cypress.preReq.title': 'Requisitos previos',
      'cypress.preReq.node': 'Node.js (versión 14 o superior)',
      'cypress.preReq.npm': 'npm o yarn como gestor de paquetes',
      'cypress.preReq.editor': 'Visual Studio Code (recomendado) o cualquier editor de código',
      'cypress.preReq.chrome': 'Google Chrome (última versión)',
      
      // GitHub steps
      'cypress.step1.title': 'Clonar el repositorio',
      'cypress.step1.desc': 'Abre tu terminal y ejecuta el siguiente comando para clonar el proyecto:',
      'cypress.step2.title': 'Verificar requisitos previos',
      'cypress.step2.desc': 'Asegúrate de tener instalado Node.js 14+ y npm o yarn:',
      'cypress.step3.title': 'Instalar dependencias del proyecto',
      'cypress.step3.desc': 'Instala todas las dependencias necesarias:',
      'cypress.step4.title': 'Instalar plugins adicionales',
      'cypress.step4.desc': 'Instala los plugins de Cypress y la librería para reportes en Word:',
      'cypress.step5.title': 'Verificar estructura del proyecto',
      'cypress.step5.desc': 'Confirma que el proyecto tenga la siguiente estructura:',
      'cypress.step6.title': 'Configurar Cypress (opcional)',
      'cypress.step6.desc': 'El archivo cypress.config.ts ya está configurado. Puedes ajustar timeouts si es necesario:',
      'cypress.step7.title': 'Verificar instalación ejecutando tests',
      'cypress.step7.desc': 'Ejecuta todos los tests para confirmar que el framework funciona:',
      'cypress.step8.title': 'Ver reportes HTML generados',
      'cypress.step8.desc': 'Abre el reporte HTML generado automáticamente:',
      'cypress.step9.title': 'Verificar reportes Word',
      'cypress.step9.desc': 'Los reportes Word se generan automáticamente en la carpeta test-reports/:',
      'cypress.step10.title': 'Ejecutar en modo interactivo',
      'cypress.step10.desc': 'Para depuración y desarrollo, ejecuta Cypress en modo interactivo:',
      
      // Guide steps
      'cypress.guide.intro.title': 'Crear un nuevo test de búsqueda en Google',
      'cypress.guide.intro.desc': 'Esta guía te mostrará cómo crear un test completo para buscar la palabra "Automatización" en Google usando el patrón Page Object Model con Cypress, TypeScript y capturas automáticas.',
      'cypress.guide1.title': 'Crear el archivo de constantes',
      'cypress.guide1.desc': 'Crea constants/SearchUrls.ts:',
      'cypress.guide2.title': 'Crear el Page Object (GoogleSearchPage.ts)',
      'cypress.guide2.desc': 'Crea pages/GoogleSearchPage.ts:',
      'cypress.guide3.title': 'Crear el archivo de test (google-search.spec.ts)',
      'cypress.guide3.desc': 'Crea tests/google-search.spec.ts:',
      'cypress.guide4.title': 'Verificar que base-page.ts existe',
      'cypress.guide4.desc': 'Confirma que utils/base-page.ts proporciona el método execute():',
      'cypress.guide5.title': 'Actualizar cypress.config.ts',
      'cypress.guide5.desc': 'Verifica que cypress.config.ts esté configurado correctamente:',
      'cypress.guide6.title': 'Actualizar package.json con scripts',
      'cypress.guide6.desc': 'Agrega scripts útiles en package.json:',
      'cypress.guide7.title': 'Ejecutar el test específico',
      'cypress.guide7.desc': 'Ejecuta solo los tests de búsqueda en Google:',
      'cypress.guide8.title': 'Ver reportes generados',
      'cypress.guide8.desc': 'Revisa los reportes HTML y Word generados automáticamente:',
      
      // Tips
      'cypress.tips.title': 'Tips adicionales',
      'cypress.tips.selectors': 'Selectores:',
      'cypress.tips.selectors.desc': 'Prioriza data-testid > id > class > xpath para mayor estabilidad',
      'cypress.tips.waits': 'Esperas:',
      'cypress.tips.waits.desc': 'Cypress maneja esperas automáticamente, pero usa',
      'cypress.tips.waits.desc2': 'cuando sea necesario',
      'cypress.tips.pageObjects': 'Page Objects:',
      'cypress.tips.pageObjects.desc': 'Hereda siempre de',
      'cypress.tips.pageObjects.desc2': 'para screenshots automáticos',
      'cypress.tips.hooks': 'Tags/Hooks:',
      'cypress.tips.hooks.desc': 'Usa',
      'cypress.tips.hooks.desc2': 'y',
      'cypress.tips.hooks.desc3': 'para setup/cleanup',
      'cypress.tips.reports': 'Reportes:',
      'cypress.tips.reports.desc': 'Screenshots automáticos con el método',
      'cypress.tips.reports.desc2': 'de BasePage',
      
      // General
      'cypress.step': 'Paso',
      'cypress.copy': 'Copiar',
      'cypress.copied': 'Copiado',
      
      // Dashboard
      'dashboard.title': 'Dashboard',
      'dashboard.content': 'Sección básica de Dashboard. Agrega aquí tu contenido.',
      'dashboard.welcome.greeting': '¡Hola! Soy José Rodrigo',
      'dashboard.welcome.description': 'QA Automation Engineer apasionado por crear soluciones de testing robustas con IA',
      'dashboard.welcome.tag.testing': 'Testing Automatizado',
      'dashboard.welcome.tag.mentor': 'Mentor',
      'dashboard.welcome.tag.learner': 'Aprendiz Continuo',
      'dashboard.stats.projects': 'Proyectos',
      'dashboard.stats.experience': 'Años Exp.',
      'dashboard.stats.technologies': 'Tecnologías',
      'dashboard.stats.certifications': 'Certificaciones',
      'dashboard.skills.title': 'Habilidades Técnicas',
      'dashboard.skills.subtitle': 'Nivel de competencia en diferentes tecnologías',
      'dashboard.achievements.title': 'Logros',
      'dashboard.achievements.subtitle': 'Experiencia y reconocimientos',
      'dashboard.achievements.experience': '9+ Años de Experiencia',
      'dashboard.achievements.experience.desc': 'En testing automatizado y desarrollo QA',
      'dashboard.achievements.projects': '25+ Proyectos Completados',
      'dashboard.achievements.projects.desc': 'Frameworks de automatización implementados',
      'dashboard.achievements.certifications': 'Certificaciones Técnicas',
      'dashboard.achievements.certifications.desc': 'En herramientas de testing y desarrollo',
      'dashboard.achievements.ai': 'IA Aplicada en Testing',
      'dashboard.achievements.ai.desc': 'Automatización inteligente y análisis predictivo',
      'dashboard.technologies.title': 'Tecnologías que domino',
      'dashboard.technologies.subtitle': 'Herramientas y frameworks para testing automatizado y desarrollo',
      'dashboard.technologies.selenium': 'Web Automation',
      'dashboard.technologies.appium': 'Mobile Automation',
      'dashboard.technologies.cypress': 'E2E Testing',
      'dashboard.technologies.playwright': 'Modern Testing',
      'dashboard.technologies.karate': 'API Testing',
      'dashboard.technologies.jenkins': 'CI/CD',
      'dashboard.technologies.docker': 'Containerization',
      'dashboard.technologies.aws': 'Cloud',
      'dashboard.technologies.chatgpt': 'AI Tools',
      'dashboard.technologies.claude': 'AI Tools',
      'dashboard.technologies.copilot': 'AI Development',
      'dashboard.cv.download': 'Ver CV Completo',
      'dashboard.cv.description': 'Descarga mi currículum actualizado',

      // Karate BDD
      'karatebdd.title': 'Karate BDD',
      'karatebdd.subtitle': 'Automatización de APIs con Karate 1.4.1 + Java + BDD + Reportes HTML Profesionales',
      'karatebdd.tab.github': 'Descarga desde GitHub',
      'karatebdd.tab.guide': 'Guía de Uso',
      'karatebdd.framework': 'Framework de Automatización',
      'karatebdd.preReq.title': 'Requisitos previos',
      'karatebdd.preReq.java': 'Java 11 o superior',
      'karatebdd.preReq.maven': 'Maven (gestor de dependencias)',
      'karatebdd.preReq.editor': 'Visual Studio Code (recomendado) o cualquier IDE compatible con Java',
      'karatebdd.preReq.extension': 'Extensión "Cucumber (Gherkin) Full Support" para VS Code (opcional)',
      
      // GitHub steps
      'karatebdd.step1.title': 'Clonar el repositorio',
      'karatebdd.step1.desc': 'Abre tu terminal y ejecuta el siguiente comando para clonar el proyecto:',
      'karatebdd.step2.title': 'Verificar requisitos previos',
      'karatebdd.step2.desc': 'Asegúrate de tener instalado Java 11+ y Maven:',
      'karatebdd.step3.title': 'Instalar dependencias del proyecto',
      'karatebdd.step3.desc': 'Instala todas las dependencias de Maven (Karate 1.4.1):',
      'karatebdd.step4.title': 'Verificar estructura del proyecto',
      'karatebdd.step4.desc': 'Confirma que el proyecto tenga la siguiente estructura:',
      'karatebdd.step5.title': 'Verificar archivo .feature',
      'karatebdd.step5.desc': 'Confirma que Posts.feature contiene los escenarios BDD en español:',
      'karatebdd.step6.title': 'Verificar instalación ejecutando tests',
      'karatebdd.step6.desc': 'Ejecuta todos los tests para confirmar que el framework funciona:',
      'karatebdd.step7.title': 'Ver reportes HTML generados',
      'karatebdd.step7.desc': 'Abre el reporte HTML de Karate generado automáticamente:',
      'karatebdd.step8.title': 'Ejecutar tests por tags',
      'karatebdd.step8.desc': 'Ejecuta solo escenarios positivos o negativos usando tags:',
      'karatebdd.step9.title': 'Verificar reportes adicionales',
      'karatebdd.step9.desc': 'Karate genera múltiples reportes HTML profesionales:',
      
      // Guide steps
      'karatebdd.guide.intro.title': 'Crear tests de API para usuarios de JSONPlaceholder',
      'karatebdd.guide.intro.desc': 'Esta guía te mostrará cómo crear tests completos para validar el endpoint de usuarios usando Karate con sintaxis BDD en español. Incluye validaciones positivas y negativas con tags para ejecución selectiva.',
      'karatebdd.guide1.title': 'Crear el archivo Feature (users-api.feature)',
      'karatebdd.guide1.desc': 'Crea src/test/resources/features/users-api.feature:',
      'karatebdd.guide2.title': 'Crear el Runner básico (UsersRunner.java)',
      'karatebdd.guide2.desc': 'Crea src/test/java/runners/UsersRunner.java:',
      'karatebdd.guide3.title': 'Crear Runner para tests positivos (UsersPositiveRunner.java)',
      'karatebdd.guide3.desc': 'Crea src/test/java/runners/UsersPositiveRunner.java:',
      'karatebdd.guide4.title': 'Crear Runner para tests negativos (UsersNegativeRunner.java)',
      'karatebdd.guide4.desc': 'Crea src/test/java/runners/UsersNegativeRunner.java:',
      'karatebdd.guide5.title': 'Verificar que pom.xml incluye Karate',
      'karatebdd.guide5.desc': 'Confirma que pom.xml tiene la dependencia de Karate 1.4.1:',
      'karatebdd.guide6.title': 'Ejecutar todos los tests de usuarios',
      'karatebdd.guide6.desc': 'Ejecuta el runner completo de usuarios:',
      'karatebdd.guide7.title': 'Ejecutar tests por tags',
      'karatebdd.guide7.desc': 'Ejecuta solo tests positivos, negativos o específicos:',
      'karatebdd.guide8.title': 'Ver reportes generados',
      'karatebdd.guide8.desc': 'Revisa los reportes HTML generados automáticamente por Karate:',
      
      // Tips
      'karatebdd.tips.title': 'Tips adicionales',
      'karatebdd.tips.tags': 'Tags organizados:',
      'karatebdd.tips.tags.desc': 'Usa @positive, @negative, @smoke, @api para ejecuciones selectivas',
      'karatebdd.tips.background': 'Background:',
      'karatebdd.tips.background.desc': 'Usa',
      'karatebdd.tips.background.desc2': 'para setup común en todos los escenarios',
      'karatebdd.tips.validations': 'Validaciones:',
      'karatebdd.tips.validations.desc': 'valida respuestas,',
      'karatebdd.tips.validations.desc2': 'valida arrays',
      'karatebdd.tips.reports': 'Reportes automáticos:',
      'karatebdd.tips.reports.desc': 'Karate genera reportes HTML profesionales sin configuración adicional',
      'karatebdd.tips.pageObjects': 'No Page Objects:',
      'karatebdd.tips.pageObjects.desc': 'Karate no necesita Page Object Model, todo está integrado en el .feature',
      'karatebdd.tips.json': 'JSON inline:',
      'karatebdd.tips.json.desc': 'Usa triple comillas',
      'karatebdd.tips.json.desc2': 'para JSON multilínea legible',
      
      // General
      'karatebdd.step': 'Paso',
      'karatebdd.copy': 'Copiar',
      'karatebdd.copied': 'Copiado',
      
      // Mentoria
      'mentoria.title': 'Mentoría en Testing Automatizado',
      'mentoria.subtitle': 'Aprende de la mano de un experto y acelera tu carrera en QA Automation',
      'mentoria.badge1': 'Sesiones 1-on-1',
      'mentoria.badge2': '100% Personalizado',
      'mentoria.badge3': 'Proyectos Reales',
      'mentoria.badge.groups': 'Grupos',
      
      // Benefits
      'mentoria.benefits.title': '¿Por qué elegir mentoría personalizada?',
      'mentoria.benefit1.title': 'Horarios Flexibles',
      'mentoria.benefit1.desc': 'Sesiones adaptadas a tu disponibilidad y zona horaria',
      'mentoria.benefit2.title': 'Enfoque Personalizado',
      'mentoria.benefit2.desc': 'Plan de aprendizaje diseñado específicamente para tus objetivos',
      'mentoria.benefit3.title': 'Proyectos Reales',
      'mentoria.benefit3.desc': 'Trabaja en casos de uso del mundo real con código profesional',
      'mentoria.benefit4.title': 'Soporte Continuo',
      'mentoria.benefit4.desc': 'Acceso a grupo privado para dudas entre sesiones',
      'mentoria.benefit5.title': 'Material de Estudio',
      'mentoria.benefit5.desc': 'Código fuente, templates y recursos descargables para tu aprendizaje',
      
      // Services
      'mentoria.services.title': 'Programas de Mentoría Disponibles',
      'mentoria.services.subtitle': 'Elige el programa que mejor se adapte a tus objetivos profesionales',
      'mentoria.service.selenium.title': 'Selenium WebDriver',
      'mentoria.service.selenium.desc': 'Domina la automatización web con el framework más utilizado del mercado',
      'mentoria.service.playwright.title': 'Playwright',
      'mentoria.service.playwright.desc': 'Aprende el framework moderno de Microsoft para testing E2E multi-navegador',
      'mentoria.service.cypress.title': 'Cypress',
      'mentoria.service.cypress.desc': 'Testing E2E moderno con recarga en tiempo real y debugging excepcional',
      'mentoria.service.karate.title': 'Karate BDD',
      'mentoria.service.karate.desc': 'Framework todo-en-uno para testing de APIs con sintaxis BDD intuitiva',
      'mentoria.service.postman.title': 'Postman + Newman',
      'mentoria.service.postman.desc': 'Testing y automatización de APIs con la herramienta líder del mercado',
      'mentoria.service.appium.title': 'Appium',
      'mentoria.service.appium.desc': 'Automatización de aplicaciones móviles (iOS y Android) nativas e híbridas',
      'mentoria.service.ai.title': 'IA Aplicada en Testing',
      'mentoria.service.ai.desc': 'Potencia tus tests con Inteligencia Artificial y herramientas modernas',
      'mentoria.topics.title': '¿Qué aprenderás?',
      'mentoria.click.expand': 'Click para ver detalles',
      'mentoria.click.collapse': 'Click para colapsar',
      
      // Methodology
      'mentoria.methodology.title': 'Metodología de Aprendizaje',
      'mentoria.method1.title': 'Evaluación Inicial',
      'mentoria.method1.desc': 'Identificamos tu nivel actual y definimos objetivos claros y alcanzables',
      'mentoria.method2.title': 'Plan Personalizado',
      'mentoria.method2.desc': 'Creamos un roadmap de aprendizaje adaptado a tus necesidades y tiempo',
      'mentoria.method3.title': 'Sesiones Prácticas',
      'mentoria.method3.desc': 'Clases en vivo con ejercicios hands-on y proyectos reales',
      'mentoria.method4.title': 'Proyecto Final',
      'mentoria.method4.desc': 'Desarrollas un framework completo de automatización listo para producción',
      
      // CTA
      'mentoria.cta.title': '¿Listo para dar el siguiente paso en tu carrera?',
      'mentoria.cta.subtitle': 'Agenda una sesión de consultoría gratuita de 30 minutos para conocer tu perfil y diseñar tu plan de aprendizaje',
      'mentoria.cta.schedule': 'Agendar Consultoría Gratuita',
      'mentoria.cta.info': 'Más Información',
      'mentoria.contact.direct': 'Contacto directo',
      
      // Groups Card
      'mentoria.groups.title': 'Mentoría para Grupos y Empresas',
      'mentoria.groups.subtitle': 'Capacitación profesional para equipos de QA y empresas',
      'mentoria.groups.desc': 'Ofrezco programas de capacitación grupal diseñados específicamente para equipos de testing y empresas que desean mejorar sus capacidades en automatización. Ideal para upskilling de equipos completos.',
      'mentoria.groups.feature1': 'Grupos de 3-10 personas',
      'mentoria.groups.feature2': 'Programa personalizado según necesidades del equipo',
      'mentoria.groups.feature3': 'Horarios corporativos flexibles',
      'mentoria.groups.feature4': 'Material y recursos compartidos',
      'mentoria.groups.feature5': 'Soporte post-capacitación incluido',
      'mentoria.groups.cta': 'Solicitar Cotización Grupal',
      
      // Custom
      'mentoria.custom.title': '¿No encuentras el programa que buscas?',
      'mentoria.custom.desc': 'Puedo diseñar un programa de mentoría completamente personalizado según tus necesidades. También ofrezco mentoría en:',
      'mentoria.custom.topics': 'API Testing con REST Assured, Performance Testing con JMeter, CI/CD con Jenkins/GitHub Actions, Docker para QA, y estrategias de testing automation desde cero.',
      
      // Topics - Selenium
      'mentoria.selenium.topic1': 'Fundamentos de Selenium WebDriver con Java/JavaScript',
      'mentoria.selenium.topic2': 'Patrón Page Object Model (POM) avanzado',
      'mentoria.selenium.topic3': 'Manejo de elementos dinámicos y esperas inteligentes',
      'mentoria.selenium.topic4': 'Integración con frameworks de testing (JUnit, TestNG, Cucumber)',
      'mentoria.selenium.topic5': 'Paralelización de tests con Selenium Grid',
      'mentoria.selenium.topic6': 'Generación de reportes profesionales (Allure, ExtentReports)',
      'mentoria.selenium.topic7': 'Mejores prácticas y manejo de errores comunes',
      
      // Topics - Playwright
      'mentoria.playwright.topic1': 'Fundamentos de Playwright con TypeScript/JavaScript',
      'mentoria.playwright.topic2': 'Auto-waiting y manejo automático de elementos',
      'mentoria.playwright.topic3': 'Testing multi-navegador (Chromium, Firefox, WebKit)',
      'mentoria.playwright.topic4': 'Interceptación de requests y mocking de APIs',
      'mentoria.playwright.topic5': 'Visual regression testing con screenshots',
      'mentoria.playwright.topic6': 'Debugging avanzado con Playwright Inspector',
      'mentoria.playwright.topic7': 'CI/CD integration y ejecución en contenedores',
      
      // Topics - Cypress
      'mentoria.cypress.topic1': 'Fundamentos de Cypress con TypeScript',
      'mentoria.cypress.topic2': 'Comandos personalizados y helpers reutilizables',
      'mentoria.cypress.topic3': 'Manejo de APIs y network stubbing',
      'mentoria.cypress.topic4': 'Page Object Model adaptado a Cypress',
      'mentoria.cypress.topic5': 'Integración con herramientas de reportes',
      'mentoria.cypress.topic6': 'Testing de componentes (Component Testing)',
      'mentoria.cypress.topic7': 'Best practices y optimización de performance',
      
      // Topics - Karate
      'mentoria.karate.topic1': 'Fundamentos de Karate DSL y sintaxis Gherkin',
      'mentoria.karate.topic2': 'Testing de APIs REST con validaciones JSON/XML',
      'mentoria.karate.topic3': 'Autenticación y manejo de tokens (OAuth, JWT)',
      'mentoria.karate.topic4': 'Data-driven testing con ejemplos y CSV',
      'mentoria.karate.topic5': 'Performance testing básico con Gatling',
      'mentoria.karate.topic6': 'Generación de reportes HTML profesionales',
      'mentoria.karate.topic7': 'Integración con CI/CD pipelines',
      
      // Topics - Postman
      'mentoria.postman.topic1': 'Fundamentos de Postman y testing de APIs',
      'mentoria.postman.topic2': 'Creación de colecciones y environments',
      'mentoria.postman.topic3': 'Scripts de pre-request y tests automatizados',
      'mentoria.postman.topic4': 'Variables dinámicas y data-driven testing',
      'mentoria.postman.topic5': 'Automatización con Newman (CLI)',
      'mentoria.postman.topic6': 'Integración con Jenkins, GitHub Actions, GitLab CI',
      'mentoria.postman.topic7': 'Generación de documentación interactiva',
      
      // Topics - Appium
      'mentoria.appium.topic1': 'Fundamentos de Appium y configuración de entornos',
      'mentoria.appium.topic2': 'Testing en dispositivos reales y emuladores',
      'mentoria.appium.topic3': 'Localizadores móviles y estrategias de selección',
      'mentoria.appium.topic4': 'Gestos táctiles y acciones móviles avanzadas',
      
      // Playwright
      'playwright.title': 'Playwright',
      'playwright.subtitle': 'Framework moderno de automatización E2E con TypeScript para testing multi-navegador',
      'playwright.tab.github': 'Descarga desde GitHub',
      'playwright.tab.guide': 'Guía de Uso',
      'playwright.framework': 'Framework de Automatización',
      'playwright.preReq.title': 'Requisitos previos',
      'playwright.preReq.node': 'Node.js 14 o superior',
      'playwright.preReq.npm': 'npm o yarn como gestor de paquetes',
      'playwright.preReq.vscode': 'Visual Studio Code (recomendado)',
      
      // GitHub steps
      'playwright.step1.title': 'Clonar el repositorio',
      'playwright.step1.desc': 'Abre tu terminal y ejecuta el siguiente comando para clonar el proyecto:',
      'playwright.step2.title': 'Verificar requisitos previos',
      'playwright.step2.desc': 'Asegúrate de tener instalado Node.js 14+ y npm:',
      'playwright.step3.title': 'Instalar dependencias del proyecto',
      'playwright.step3.desc': 'Instala todas las dependencias necesarias con npm:',
      'playwright.step4.title': 'Instalar navegadores de Playwright',
      'playwright.step4.desc': 'Descarga e instala los navegadores (Chromium, Firefox, WebKit):',
      'playwright.step5.title': 'Instalar librería para reportes en Word',
      'playwright.step5.desc': 'Instala la librería docx para generar reportes personalizados:',
      'playwright.step6.title': 'Verificar estructura del proyecto',
      'playwright.step6.desc': 'Confirma que el proyecto tenga la siguiente estructura:',
      'playwright.step7.title': 'Ejecutar las pruebas',
      'playwright.step7.desc': 'Ejecuta todos los tests para verificar que el framework funciona correctamente:',
      'playwright.step8.title': 'Ver el reporte HTML',
      'playwright.step8.desc': 'Visualiza el reporte HTML generado automáticamente:',
      
      // Guide steps
      'playwright.guide.intro.title': 'Crear un nuevo test de búsqueda en Google',
      'playwright.guide.intro.desc': 'Esta guía te mostrará cómo crear un test completo para buscar la palabra "Automatización" en Google usando el patrón Page Object Model con Playwright y TypeScript.',
      'playwright.guide1.title': 'Crear el archivo de constantes',
      'playwright.guide1.desc': 'Crea constants/search-urls.ts para centralizar las URLs:',
      'playwright.guide2.title': 'Crear el Page Object (GoogleSearchPage.ts)',
      'playwright.guide2.desc': 'Crea pages/GoogleSearchPage.ts con los selectores y métodos:',
      'playwright.guide3.title': 'Crear el archivo de test (google-search.spec.ts)',
      'playwright.guide3.desc': 'Crea tests/google-search.spec.ts con los casos de prueba:',
      'playwright.guide4.title': 'Verificar BasePage existe',
      'playwright.guide4.desc': 'Confirma que utils/base-page.ts está en el proyecto (ya viene incluido):',
      'playwright.guide5.title': 'Configurar playwright.config.ts (opcional)',
      'playwright.guide5.desc': 'Si quieres ejecutar solo en Chromium, verifica la configuración:',
      'playwright.guide6.title': 'Ejecutar el test específico',
      'playwright.guide6.desc': 'Ejecuta solo el test de búsqueda en Google:',
      'playwright.guide7.title': 'Ejecutar con interfaz gráfica (UI Mode)',
      'playwright.guide7.desc': 'Para depurar visualmente el test paso a paso:',
      'playwright.guide8.title': 'Ver reportes generados',
      'playwright.guide8.desc': 'Revisa los reportes HTML y Word generados automáticamente:',
      
      // Tips
      'playwright.tips.title': 'Tips adicionales',
      'playwright.tips.selectors': 'Prioriza selectores por role, label o data-testid',
      'playwright.tips.waits': 'Playwright espera automáticamente, pero usa',
      'playwright.tips.waits.code': 'waitForSelector()',
      'playwright.tips.waits.when': 'cuando sea necesario',
      'playwright.tips.screenshots': 'Se capturan automáticamente con el método',
      'playwright.tips.screenshots.code': 'execute()',
      'playwright.tips.reports': 'Se generan automáticamente en',
      'playwright.tips.reports.path': 'test-reports/',
      'playwright.tips.uimode': 'Usa',
      'playwright.tips.uimode.code': '--ui',
      'playwright.tips.uimode.desc': 'para depuración visual interactiva',
      
      // General labels
      'playwright.step': 'Paso',
      'playwright.copy': 'Copiar',
      'playwright.copied': 'Copiado',
      'mentoria.appium.topic5': 'Page Object Model para aplicaciones móviles',
      'mentoria.appium.topic6': 'Integración con frameworks (TestNG, Cucumber)',
      'mentoria.appium.topic7': 'Testing paralelo en múltiples dispositivos',

      // Topics - AI
      'mentoria.ai.topic1': 'Introducción a IA/ML en QA Automation',
      'mentoria.ai.topic2': 'Generación automática de tests con IA (ChatGPT, Claude)',
      'mentoria.ai.topic3': 'Visual testing inteligente con herramientas AI',
      'mentoria.ai.topic4': 'Self-healing tests con selectores dinámicos',
      'mentoria.ai.topic5': 'Análisis predictivo de fallos en tests',
      'mentoria.ai.topic6': 'Optimización de test suites con ML',
      'mentoria.ai.topic7': 'Herramientas: Testim, Mabl, Applitools, Functionize',
      
      // Selenium
      'selenium.title': 'Selenium',
      'selenium.subtitle': 'Automatización web profesional con Selenium WebDriver, Java y Cucumber BDD',
      'selenium.tab.github': 'Descarga desde GitHub',
      'selenium.tab.guide': 'Guía de Uso',
      'selenium.framework': 'Framework de Automatización',
      'selenium.preReq.title': 'Requisitos previos',
      'selenium.preReq.java': 'Java JDK 11 o superior',
      'selenium.preReq.maven': 'Maven 3.6 o superior',
      'selenium.preReq.ide': 'IntelliJ IDEA (recomendado) o cualquier IDE Java',
      'selenium.preReq.chrome': 'Google Chrome (última versión)',
      
      // GitHub steps
      'selenium.step1.title': 'Clonar el repositorio',
      'selenium.step1.desc': 'Abre tu terminal y ejecuta el siguiente comando para clonar el proyecto:',
      'selenium.step2.title': 'Verificar requisitos previos',
      'selenium.step2.desc': 'Asegúrate de tener instalado Java JDK 11+, Maven 3.6+ y Google Chrome:',
      'selenium.step3.title': 'Instalar dependencias del proyecto',
      'selenium.step3.desc': 'Instala todas las dependencias de Maven:',
      'selenium.step4.title': 'Verificar estructura del proyecto',
      'selenium.step4.desc': 'Confirma que el proyecto tenga la siguiente estructura:',
      'selenium.step5.title': 'Configurar WebDriver (opcional)',
      'selenium.step5.desc': 'El proyecto usa WebDriverManager para gestión automática de drivers. Si necesitas configuración manual, edita DriverManager.java:',
      'selenium.step6.title': 'Verificar instalación ejecutando tests',
      'selenium.step6.desc': 'Ejecuta todos los tests para confirmar que el framework funciona:',
      'selenium.step7.title': 'Ver reportes HTML generados',
      'selenium.step7.desc': 'Abre el reporte HTML de Cucumber generado automáticamente:',
      'selenium.step8.title': 'Verificar reportes Word',
      'selenium.step8.desc': 'Los reportes Word se generan automáticamente en la carpeta test-reports/:',
      
      // Guide steps
      'selenium.guide.intro.title': 'Crear un nuevo test de búsqueda en Google',
      'selenium.guide.intro.desc': 'Esta guía te mostrará cómo crear un test completo para buscar la palabra "Automatización" en Google usando el patrón Page Object Model con Selenium WebDriver, Java y Cucumber.',
      'selenium.guide1.title': 'Crear el archivo de constantes',
      'selenium.guide1.desc': 'Crea src/main/java/com/selenium/constants/SearchUrls.java:',
      'selenium.guide2.title': 'Crear el Page Object (GoogleSearchPage.java)',
      'selenium.guide2.desc': 'Crea src/main/java/com/selenium/pages/GoogleSearchPage.java:',
      'selenium.guide3.title': 'Crear el archivo Feature (google-search.feature)',
      'selenium.guide3.desc': 'Crea src/test/resources/features/google-search.feature:',
      'selenium.guide4.title': 'Crear Step Definitions (GoogleSearchSteps.java)',
      'selenium.guide4.desc': 'Crea src/test/java/com/selenium/stepdefinitions/GoogleSearchSteps.java:',
      'selenium.guide5.title': 'Verificar que Hooks.java existe',
      'selenium.guide5.desc': 'Confirma que src/test/java/com/selenium/hooks/Hooks.java gestiona el ciclo de vida:',
      'selenium.guide6.title': 'Actualizar TestRunner.java',
      'selenium.guide6.desc': 'Verifica que src/test/java/com/selenium/runners/TestRunner.java incluya el nuevo feature:',
      'selenium.guide7.title': 'Ejecutar el test específico',
      'selenium.guide7.desc': 'Ejecuta solo los tests de búsqueda en Google usando tags:',
      'selenium.guide8.title': 'Ver reportes generados',
      'selenium.guide8.desc': 'Revisa los reportes HTML y Word generados automáticamente:',
      
      // Tips
      'selenium.tips.title': 'Tips adicionales',
      'selenium.tips.selectors': 'Prioriza id > name > className > xpath para mayor estabilidad',
      'selenium.tips.waits': 'Usa',
      'selenium.tips.waits.code1': 'WebDriverWait',
      'selenium.tips.waits.with': 'con',
      'selenium.tips.waits.code2': 'ExpectedConditions',
      'selenium.tips.pagefactory': 'Usa anotaciones',
      'selenium.tips.pagefactory.code': '@FindBy',
      'selenium.tips.pagefactory.desc': 'para inicializar elementos',
      'selenium.tips.tags': 'Organiza tests con @smoke, @regression, @negative para ejecuciones selectivas',
      'selenium.tips.screenshots': 'Screenshots automáticos con el método',
      'selenium.tips.screenshots.code': 'execute()',
      'selenium.tips.screenshots.desc': 'de BasePage',
      
      // General labels
      'selenium.step': 'Paso',
      'selenium.copy': 'Copiar',
      'selenium.copied': 'Copiado',
    },
    en: {
      // Header
      'header.name': 'José Rodrigo Escutia Ríos',
      'header.downloadCV': 'Download CV',
      'header.downloadCVShort': 'CV',
      
      // Sidebar
      'sidebar.dashboard': 'Dashboard',
      'sidebar.appium': 'Appium',
      'sidebar.cypress': 'Cypress',
      'sidebar.karatebdd': 'Karate BDD',
      'sidebar.mentoria': 'Mentoring',
      'sidebar.playwright': 'Playwright',
      'sidebar.selenium': 'Selenium',
      
      // Languages
      'lang.spanish': 'Español',
      'lang.english': 'English',
      
      // Appium
      'appium.title': 'Appium',
      'appium.subtitle': 'Professional mobile automation with Appium and Java',
      'appium.tab.github': 'Download from GitHub',
      'appium.tab.guide': 'Usage Guide',
      'appium.framework': 'Automation Framework',
      'appium.preReq.title': 'Prerequisites',
      'appium.preReq.java': 'Java JDK 17 or higher',
      'appium.preReq.maven': 'Maven 3.8 or higher',
      'appium.preReq.node': 'Node.js and npm',
      'appium.preReq.android': 'Android SDK configured',
      'appium.preReq.device': 'Android device with USB debugging enabled',
      
      // GitHub steps
      'appium.step1.title': 'Clone the repository',
      'appium.step1.desc': 'Open your terminal and run the following command to clone the project:',
      'appium.step2.title': 'Verify prerequisites',
      'appium.step2.desc': 'Make sure you have Java JDK 17+, Maven 3.8+, Node.js and Appium installed:',
      'appium.step3.title': 'Install Appium and drivers',
      'appium.step3.desc': 'If you don\'t have Appium installed, run:',
      'appium.step4.title': 'Configure Android SDK',
      'appium.step4.desc': 'Set the ANDROID_HOME environment variable (Windows PowerShell):',
      'appium.step5.title': 'Install project dependencies',
      'appium.step5.desc': 'Install all Maven dependencies:',
      'appium.step6.title': 'Configure Android device',
      'appium.step6.desc': 'Edit the config.properties file with your device data:',
      'appium.step7.title': 'Start Appium Server',
      'appium.step7.desc': 'In a separate terminal, start the Appium server:',
      'appium.step8.title': 'Run tests',
      'appium.step8.desc': 'Connect your Android device and run the tests:',
      
      // Guide steps
      'appium.guide.intro.title': 'Create a new Google search test',
      'appium.guide.intro.desc': 'This guide will show you how to create a complete test to search for the word "Automation" in Google Chrome using the Page Object Model pattern with Cucumber BDD.',
      'appium.guide1.title': 'Create the Feature file',
      'appium.guide1.desc': 'Create a new file at src/test/resources/features/busqueda_automatizacion.feature:',
      'appium.guide2.title': 'Create the Page Object (GoogleSearchPage.java)',
      'appium.guide2.desc': 'Create src/main/java/com/mobile/automation/pages/GoogleSearchPage.java:',
      'appium.guide3.title': 'Create Step Definitions (BusquedaAutomatizacionSteps.java)',
      'appium.guide3.desc': 'Create src/test/java/com/mobile/automation/stepdefinitions/BusquedaAutomatizacionSteps.java:',
      'appium.guide4.title': 'Update TestRunner.java (if needed)',
      'appium.guide4.desc': 'Verify that your TestRunner includes the new feature:',
      'appium.guide5.title': 'Configure the device',
      'appium.guide5.desc': 'Get your device ID and update config.properties:',
      'appium.guide6.title': 'Start Appium Server',
      'appium.guide6.desc': 'Open a terminal and run Appium:',
      'appium.guide7.title': 'Run the test',
      'appium.guide7.desc': 'Execute the new test from another terminal:',
      'appium.guide8.title': 'View the report',
      'appium.guide8.desc': 'Once execution is complete, open the HTML report:',
      
      // Tips
      'appium.tips.title': 'Additional tips',
      'appium.tips.locators': 'Locators:',
      'appium.tips.locators.desc': 'Use Appium Inspector to identify elements correctly',
      'appium.tips.waits': 'Waits:',
      'appium.tips.waits.desc': 'Implement explicit waits with',
      'appium.tips.tags': 'Tags:',
      'appium.tips.tags.desc': 'Use tags like @smoke, @regression to organize your tests',
      'appium.tips.screenshots': 'Screenshots:',
      'appium.tips.screenshots.desc': 'Errors automatically capture screenshots',
      'appium.tips.reports': 'Reports:',
      'appium.tips.reports.desc': 'Review the HTML report generated with ExtentReports for detailed analysis',
      
      // General
      'appium.step': 'Step',
      'appium.copy': 'Copy',
      'appium.copied': 'Copied',
      
      // Cypress
      'cypress.title': 'Cypress',
      'cypress.subtitle': 'E2E Automation with Cypress + TypeScript + Page Object Model + Word Reports',
      'cypress.tab.github': 'Download from GitHub',
      'cypress.tab.guide': 'Usage Guide',
      'cypress.framework': 'Automation Framework',
      'cypress.preReq.title': 'Prerequisites',
      'cypress.preReq.node': 'Node.js (version 14 or higher)',
      'cypress.preReq.npm': 'npm or yarn as package manager',
      'cypress.preReq.editor': 'Visual Studio Code (recommended) or any code editor',
      'cypress.preReq.chrome': 'Google Chrome (latest version)',
      
      // GitHub steps
      'cypress.step1.title': 'Clone the repository',
      'cypress.step1.desc': 'Open your terminal and run the following command to clone the project:',
      'cypress.step2.title': 'Verify prerequisites',
      'cypress.step2.desc': 'Make sure you have Node.js 14+ and npm or yarn installed:',
      'cypress.step3.title': 'Install project dependencies',
      'cypress.step3.desc': 'Install all necessary dependencies:',
      'cypress.step4.title': 'Install additional plugins',
      'cypress.step4.desc': 'Install Cypress plugins and the library for Word reports:',
      'cypress.step5.title': 'Verify project structure',
      'cypress.step5.desc': 'Confirm that the project has the following structure:',
      'cypress.step6.title': 'Configure Cypress (optional)',
      'cypress.step6.desc': 'The cypress.config.ts file is already configured. You can adjust timeouts if needed:',
      'cypress.step7.title': 'Verify installation by running tests',
      'cypress.step7.desc': 'Run all tests to confirm the framework works:',
      'cypress.step8.title': 'View generated HTML reports',
      'cypress.step8.desc': 'Open the automatically generated HTML report:',
      'cypress.step9.title': 'Verify Word reports',
      'cypress.step9.desc': 'Word reports are automatically generated in the test-reports/ folder:',
      'cypress.step10.title': 'Run in interactive mode',
      'cypress.step10.desc': 'For debugging and development, run Cypress in interactive mode:',
      
      // Guide steps
      'cypress.guide.intro.title': 'Create a new Google search test',
      'cypress.guide.intro.desc': 'This guide will show you how to create a complete test to search for the word "Automation" in Google using the Page Object Model pattern with Cypress, TypeScript, and automatic screenshots.',
      'cypress.guide1.title': 'Create the constants file',
      'cypress.guide1.desc': 'Create constants/SearchUrls.ts:',
      'cypress.guide2.title': 'Create the Page Object (GoogleSearchPage.ts)',
      'cypress.guide2.desc': 'Create pages/GoogleSearchPage.ts:',
      'cypress.guide3.title': 'Create the test file (google-search.spec.ts)',
      'cypress.guide3.desc': 'Create tests/google-search.spec.ts:',
      'cypress.guide4.title': 'Verify that base-page.ts exists',
      'cypress.guide4.desc': 'Confirm that utils/base-page.ts provides the execute() method:',
      'cypress.guide5.title': 'Update cypress.config.ts',
      'cypress.guide5.desc': 'Verify that cypress.config.ts is configured correctly:',
      'cypress.guide6.title': 'Update package.json with scripts',
      'cypress.guide6.desc': 'Add useful scripts in package.json:',
      'cypress.guide7.title': 'Run the specific test',
      'cypress.guide7.desc': 'Execute only the Google search tests:',
      'cypress.guide8.title': 'View generated reports',
      'cypress.guide8.desc': 'Review the automatically generated HTML and Word reports:',
      
      // Tips
      'cypress.tips.title': 'Additional tips',
      'cypress.tips.selectors': 'Selectors:',
      'cypress.tips.selectors.desc': 'Prioritize data-testid > id > class > xpath for greater stability',
      'cypress.tips.waits': 'Waits:',
      'cypress.tips.waits.desc': 'Cypress handles waits automatically, but use',
      'cypress.tips.waits.desc2': 'when necessary',
      'cypress.tips.pageObjects': 'Page Objects:',
      'cypress.tips.pageObjects.desc': 'Always inherit from',
      'cypress.tips.pageObjects.desc2': 'for automatic screenshots',
      'cypress.tips.hooks': 'Tags/Hooks:',
      'cypress.tips.hooks.desc': 'Use',
      'cypress.tips.hooks.desc2': 'and',
      'cypress.tips.hooks.desc3': 'for setup/cleanup',
      'cypress.tips.reports': 'Reports:',
      'cypress.tips.reports.desc': 'Automatic screenshots with the',
      'cypress.tips.reports.desc2': 'method from BasePage',
      
      // General
      'cypress.step': 'Step',
      'cypress.copy': 'Copy',
      'cypress.copied': 'Copied',
      
      // Dashboard
      'dashboard.title': 'Dashboard',
      'dashboard.content': 'Basic Dashboard section. Add your content here.',
      'dashboard.welcome.greeting': 'Hi! I\'m José Rodrigo',
      'dashboard.welcome.description': 'QA Automation Engineer passionate about creating robust testing solutions with AI',
      'dashboard.welcome.tag.testing': 'Automated Testing',
      'dashboard.welcome.tag.mentor': 'Mentor',
      'dashboard.welcome.tag.learner': 'Continuous Learner',
      'dashboard.stats.projects': 'Projects',
      'dashboard.stats.experience': 'Years Exp.',
      'dashboard.stats.technologies': 'Technologies',
      'dashboard.stats.certifications': 'Certifications',
      'dashboard.skills.title': 'Technical Skills',
      'dashboard.skills.subtitle': 'Competence level in different technologies',
      'dashboard.achievements.title': 'Achievements',
      'dashboard.achievements.subtitle': 'Experience and recognitions',
      'dashboard.achievements.experience': '9+ Years of Experience',
      'dashboard.achievements.experience.desc': 'In automated testing and QA development',
      'dashboard.achievements.projects': '25+ Completed Projects',
      'dashboard.achievements.projects.desc': 'Automation frameworks implemented',
      'dashboard.achievements.certifications': 'Technical Certifications',
      'dashboard.achievements.certifications.desc': 'In testing and development tools',
      'dashboard.achievements.ai': 'AI Applied in Testing',
      'dashboard.achievements.ai.desc': 'Intelligent automation and predictive analysis',
      'dashboard.technologies.title': 'Technologies I master',
      'dashboard.technologies.subtitle': 'Tools and frameworks for automated testing and development',
      'dashboard.technologies.selenium': 'Web Automation',
      'dashboard.technologies.appium': 'Mobile Automation',
      'dashboard.technologies.cypress': 'E2E Testing',
      'dashboard.technologies.playwright': 'Modern Testing',
      'dashboard.technologies.karate': 'API Testing',
      'dashboard.technologies.jenkins': 'CI/CD',
      'dashboard.technologies.docker': 'Containerization',
      'dashboard.technologies.aws': 'Cloud',
      'dashboard.technologies.chatgpt': 'AI Tools',
      'dashboard.technologies.claude': 'AI Tools',
      'dashboard.technologies.copilot': 'AI Development',
      'dashboard.cv.download': 'Ver CV Completo',
      'dashboard.cv.description': 'Descarga mi currículum actualizado',

      // Karate BDD
      'karatebdd.title': 'Karate BDD',
      'karatebdd.subtitle': 'API Automation with Karate 1.4.1 + Java + BDD + Professional HTML Reports',
      'karatebdd.tab.github': 'Download from GitHub',
      'karatebdd.tab.guide': 'Usage Guide',
      'karatebdd.framework': 'Automation Framework',
      'karatebdd.preReq.title': 'Prerequisites',
      'karatebdd.preReq.java': 'Java 11 or higher',
      'karatebdd.preReq.maven': 'Maven (dependency manager)',
      'karatebdd.preReq.editor': 'Visual Studio Code (recommended) or any Java-compatible IDE',
      'karatebdd.preReq.extension': 'Extension "Cucumber (Gherkin) Full Support" for VS Code (optional)',
      
      // GitHub steps
      'karatebdd.step1.title': 'Clone the repository',
      'karatebdd.step1.desc': 'Open your terminal and run the following command to clone the project:',
      'karatebdd.step2.title': 'Verify prerequisites',
      'karatebdd.step2.desc': 'Make sure you have Java 11+ and Maven installed:',
      'karatebdd.step3.title': 'Install project dependencies',
      'karatebdd.step3.desc': 'Install all Maven dependencies (Karate 1.4.1):',
      'karatebdd.step4.title': 'Verify project structure',
      'karatebdd.step4.desc': 'Confirm that the project has the following structure:',
      'karatebdd.step5.title': 'Verify .feature file',
      'karatebdd.step5.desc': 'Confirm that Posts.feature contains BDD scenarios in Spanish:',
      'karatebdd.step6.title': 'Verify installation by running tests',
      'karatebdd.step6.desc': 'Run all tests to confirm the framework works:',
      'karatebdd.step7.title': 'View generated HTML reports',
      'karatebdd.step7.desc': 'Open the automatically generated Karate HTML report:',
      'karatebdd.step8.title': 'Run tests by tags',
      'karatebdd.step8.desc': 'Execute only positive or negative scenarios using tags:',
      'karatebdd.step9.title': 'Verify additional reports',
      'karatebdd.step9.desc': 'Karate generates multiple professional HTML reports:',
      
      // Guide steps
      'karatebdd.guide.intro.title': 'Create API tests for JSONPlaceholder users',
      'karatebdd.guide.intro.desc': 'This guide will show you how to create complete tests to validate the users endpoint using Karate with BDD syntax in Spanish. Includes positive and negative validations with tags for selective execution.',
      'karatebdd.guide1.title': 'Create the Feature file (users-api.feature)',
      'karatebdd.guide1.desc': 'Create src/test/resources/features/users-api.feature:',
      'karatebdd.guide2.title': 'Create the basic Runner (UsersRunner.java)',
      'karatebdd.guide2.desc': 'Create src/test/java/runners/UsersRunner.java:',
      'karatebdd.guide3.title': 'Create Runner for positive tests (UsersPositiveRunner.java)',
      'karatebdd.guide3.desc': 'Create src/test/java/runners/UsersPositiveRunner.java:',
      'karatebdd.guide4.title': 'Create Runner for negative tests (UsersNegativeRunner.java)',
      'karatebdd.guide4.desc': 'Create src/test/java/runners/UsersNegativeRunner.java:',
      'karatebdd.guide5.title': 'Verify that pom.xml includes Karate',
      'karatebdd.guide5.desc': 'Confirm that pom.xml has the Karate 1.4.1 dependency:',
      'karatebdd.guide6.title': 'Run all user tests',
      'karatebdd.guide6.desc': 'Execute the complete users runner:',
      'karatebdd.guide7.title': 'Run tests by tags',
      'karatebdd.guide7.desc': 'Execute only positive, negative, or specific tests:',
      'karatebdd.guide8.title': 'View generated reports',
      'karatebdd.guide8.desc': 'Review the HTML reports automatically generated by Karate:',
      
      // Tips
      'karatebdd.tips.title': 'Additional tips',
      'karatebdd.tips.tags': 'Organized tags:',
      'karatebdd.tips.tags.desc': 'Use @positive, @negative, @smoke, @api for selective executions',
      'karatebdd.tips.background': 'Background:',
      'karatebdd.tips.background.desc': 'Use',
      'karatebdd.tips.background.desc2': 'for common setup in all scenarios',
      'karatebdd.tips.validations': 'Validations:',
      'karatebdd.tips.validations.desc': 'validates responses,',
      'karatebdd.tips.validations.desc2': 'validates arrays',
      'karatebdd.tips.reports': 'Automatic reports:',
      'karatebdd.tips.reports.desc': 'Karate generates professional HTML reports without additional configuration',
      'karatebdd.tips.pageObjects': 'No Page Objects:',
      'karatebdd.tips.pageObjects.desc': 'Karate doesn\'t need Page Object Model, everything is integrated in the .feature',
      'karatebdd.tips.json': 'Inline JSON:',
      'karatebdd.tips.json.desc': 'Use triple quotes',
      'karatebdd.tips.json.desc2': 'for readable multiline JSON',
      
      // General
      'karatebdd.step': 'Step',
      'karatebdd.copy': 'Copy',
      'karatebdd.copied': 'Copied',
      
      // Mentoria
      'mentoria.title': 'Automated Testing Mentoring',
      'mentoria.subtitle': 'Learn from an expert and accelerate your QA Automation career',
      'mentoria.badge1': '1-on-1 Sessions',
      'mentoria.badge2': '100% Personalized',
      'mentoria.badge3': 'Real Projects',
      'mentoria.badge.groups': 'Groups',
      
      // Benefits
      'mentoria.benefits.title': 'Why choose personalized mentoring?',
      'mentoria.benefit1.title': 'Flexible Schedules',
      'mentoria.benefit1.desc': 'Sessions adapted to your availability and time zone',
      'mentoria.benefit2.title': 'Personalized Approach',
      'mentoria.benefit2.desc': 'Learning plan designed specifically for your goals',
      'mentoria.benefit3.title': 'Real Projects',
      'mentoria.benefit3.desc': 'Work on real-world use cases with professional code',
      'mentoria.benefit4.title': 'Continuous Support',
      'mentoria.benefit4.desc': 'Access to private group for questions between sessions',
      'mentoria.benefit5.title': 'Study Materials',
      'mentoria.benefit5.desc': 'Source code, templates, and downloadable resources for your learning',
      
      // Services
      'mentoria.services.title': 'Available Mentoring Programs',
      'mentoria.services.subtitle': 'Choose the program that best fits your professional goals',
      'mentoria.service.selenium.title': 'Selenium WebDriver',
      'mentoria.service.selenium.desc': 'Master web automation with the most used framework in the market',
      'mentoria.service.playwright.title': 'Playwright',
      'mentoria.service.playwright.desc': 'Learn Microsoft\'s modern framework for multi-browser E2E testing',
      'mentoria.service.cypress.title': 'Cypress',
      'mentoria.service.cypress.desc': 'Modern E2E testing with real-time reload and exceptional debugging',
      'mentoria.service.karate.title': 'Karate BDD',
      'mentoria.service.karate.desc': 'All-in-one framework for API testing with intuitive BDD syntax',
      'mentoria.service.postman.title': 'Postman + Newman',
      'mentoria.service.postman.desc': 'API testing and automation with the market-leading tool',
      'mentoria.service.appium.title': 'Appium',
      'mentoria.service.appium.desc': 'Automation of native and hybrid mobile applications (iOS and Android)',
      'mentoria.service.ai.title': 'AI Applied in Testing',
      'mentoria.service.ai.desc': 'Enhance your tests with Artificial Intelligence and modern tools',
      'mentoria.topics.title': 'What will you learn?',
      'mentoria.click.expand': 'Click to view details',
      'mentoria.click.collapse': 'Click to collapse',
      
      // Methodology
      'mentoria.methodology.title': 'Learning Methodology',
      'mentoria.method1.title': 'Initial Assessment',
      'mentoria.method1.desc': 'We identify your current level and define clear and achievable goals',
      'mentoria.method2.title': 'Personalized Plan',
      'mentoria.method2.desc': 'We create a learning roadmap adapted to your needs and time',
      'mentoria.method3.title': 'Practical Sessions',
      'mentoria.method3.desc': 'Live classes with hands-on exercises and real projects',
      'mentoria.method4.title': 'Final Project',
      'mentoria.method4.desc': 'You develop a complete automation framework ready for production',
      
      // CTA
      'mentoria.cta.title': 'Ready to take the next step in your career?',
      'mentoria.cta.subtitle': 'Schedule a free 30-minute consultation session to know your profile and design your learning plan',
      'mentoria.cta.schedule': 'Schedule Free Consultation',
      'mentoria.cta.info': 'More Information',
      'mentoria.contact.direct': 'Direct contact',
      
      // Groups Card
      'mentoria.groups.title': 'Mentoring for Groups and Companies',
      'mentoria.groups.subtitle': 'Professional training for QA teams and companies',
      'mentoria.groups.desc': 'I offer group training programs specifically designed for testing teams and companies looking to improve their automation capabilities. Ideal for upskilling entire teams.',
      'mentoria.groups.feature1': 'Groups of 3-10 people',
      'mentoria.groups.feature2': 'Custom program according to team needs',
      'mentoria.groups.feature3': 'Flexible corporate schedules',
      'mentoria.groups.feature4': 'Shared materials and resources',
      'mentoria.groups.feature5': 'Post-training support included',
      'mentoria.groups.cta': 'Request Group Quote',
      
      // Custom
      'mentoria.custom.title': 'Can\'t find the program you\'re looking for?',
      'mentoria.custom.desc': 'I can design a completely personalized mentoring program according to your needs. I also offer mentoring in:',
      'mentoria.custom.topics': 'API Testing with REST Assured, Performance Testing with JMeter, CI/CD with Jenkins/GitHub Actions, Docker for QA, and test automation strategies from scratch.',
      
      // Topics - Selenium
      'mentoria.selenium.topic1': 'Selenium WebDriver fundamentals with Java/JavaScript',
      'mentoria.selenium.topic2': 'Advanced Page Object Model (POM) pattern',
      'mentoria.selenium.topic3': 'Dynamic element handling and smart waits',
      'mentoria.selenium.topic4': 'Integration with testing frameworks (JUnit, TestNG, Cucumber)',
      'mentoria.selenium.topic5': 'Test parallelization with Selenium Grid',
      'mentoria.selenium.topic6': 'Professional report generation (Allure, ExtentReports)',
      'mentoria.selenium.topic7': 'Best practices and common error handling',
      
      // Topics - Playwright
      'mentoria.playwright.topic1': 'Playwright fundamentals with TypeScript/JavaScript',
      'mentoria.playwright.topic2': 'Auto-waiting and automatic element handling',
      'mentoria.playwright.topic3': 'Multi-browser testing (Chromium, Firefox, WebKit)',
      'mentoria.playwright.topic4': 'Request interception and API mocking',
      'mentoria.playwright.topic5': 'Visual regression testing with screenshots',
      'mentoria.playwright.topic6': 'Advanced debugging with Playwright Inspector',
      'mentoria.playwright.topic7': 'CI/CD integration and container execution',
      
      // Topics - Cypress
      'mentoria.cypress.topic1': 'Cypress fundamentals with TypeScript',
      'mentoria.cypress.topic2': 'Custom commands and reusable helpers',
      'mentoria.cypress.topic3': 'API handling and network stubbing',
      'mentoria.cypress.topic4': 'Page Object Model adapted to Cypress',
      'mentoria.cypress.topic5': 'Integration with reporting tools',
      'mentoria.cypress.topic6': 'Component Testing',
      'mentoria.cypress.topic7': 'Best practices and performance optimization',
      
      // Topics - Karate
      'mentoria.karate.topic1': 'Karate DSL fundamentals and Gherkin syntax',
      'mentoria.karate.topic2': 'REST API testing with JSON/XML validations',
      'mentoria.karate.topic3': 'Authentication and token handling (OAuth, JWT)',
      'mentoria.karate.topic4': 'Data-driven testing with examples and CSV',
      'mentoria.karate.topic5': 'Basic performance testing with Gatling',
      'mentoria.karate.topic6': 'Professional HTML report generation',
      'mentoria.karate.topic7': 'CI/CD pipeline integration',
      
      // Topics - Postman
      'mentoria.postman.topic1': 'Postman fundamentals and API testing',
      'mentoria.postman.topic2': 'Creating collections and environments',
      'mentoria.postman.topic3': 'Pre-request scripts and automated tests',
      'mentoria.postman.topic4': 'Dynamic variables and data-driven testing',
      'mentoria.postman.topic5': 'Automation with Newman (CLI)',
      'mentoria.postman.topic6': 'Integration with Jenkins, GitHub Actions, GitLab CI',
      'mentoria.postman.topic7': 'Interactive documentation generation',
      
      // Topics - Appium
      'mentoria.appium.topic1': 'Appium fundamentals and environment setup',
      'mentoria.appium.topic2': 'Testing on real devices and emulators',
      'mentoria.appium.topic3': 'Mobile locators and selection strategies',
      'mentoria.appium.topic4': 'Touch gestures and advanced mobile actions',
      'mentoria.appium.topic5': 'Page Object Model for mobile applications',
      'mentoria.appium.topic6': 'Framework integration (TestNG, Cucumber)',
      'mentoria.appium.topic7': 'Parallel testing on multiple devices',
      
      // Topics - AI
      'mentoria.ai.topic1': 'Introduction to AI/ML in QA Automation',
      'mentoria.ai.topic2': 'Automatic test generation with AI (ChatGPT, Claude)',
      'mentoria.ai.topic3': 'Intelligent visual testing with AI tools',
      'mentoria.ai.topic4': 'Self-healing tests with dynamic selectors',
      'mentoria.ai.topic5': 'Predictive analysis of test failures',
      'mentoria.ai.topic6': 'Test suite optimization with ML',
      'mentoria.ai.topic7': 'Tools: Testim, Mabl, Applitools, Functionize',
      
      // Playwright
      'playwright.title': 'Playwright',
      'playwright.subtitle': 'Modern E2E automation framework with TypeScript for multi-browser testing',
      'playwright.tab.github': 'Download from GitHub',
      'playwright.tab.guide': 'Usage Guide',
      'playwright.framework': 'Automation Framework',
      'playwright.preReq.title': 'Prerequisites',
      'playwright.preReq.node': 'Node.js 14 or higher',
      'playwright.preReq.npm': 'npm or yarn as package manager',
      'playwright.preReq.vscode': 'Visual Studio Code (recommended)',
      
      // GitHub steps
      'playwright.step1.title': 'Clone the repository',
      'playwright.step1.desc': 'Open your terminal and run the following command to clone the project:',
      'playwright.step2.title': 'Verify prerequisites',
      'playwright.step2.desc': 'Make sure you have Node.js 14+ and npm installed:',
      'playwright.step3.title': 'Install project dependencies',
      'playwright.step3.desc': 'Install all required dependencies with npm:',
      'playwright.step4.title': 'Install Playwright browsers',
      'playwright.step4.desc': 'Download and install browsers (Chromium, Firefox, WebKit):',
      'playwright.step5.title': 'Install Word report library',
      'playwright.step5.desc': 'Install the docx library to generate custom reports:',
      'playwright.step6.title': 'Verify project structure',
      'playwright.step6.desc': 'Confirm that the project has the following structure:',
      'playwright.step7.title': 'Run the tests',
      'playwright.step7.desc': 'Execute all tests to verify the framework works correctly:',
      'playwright.step8.title': 'View the HTML report',
      'playwright.step8.desc': 'Visualize the automatically generated HTML report:',
      
      // Guide steps
      'playwright.guide.intro.title': 'Create a new Google search test',
      'playwright.guide.intro.desc': 'This guide will show you how to create a complete test to search for the word "Automation" on Google using the Page Object Model pattern with Playwright and TypeScript.',
      'playwright.guide1.title': 'Create the constants file',
      'playwright.guide1.desc': 'Create constants/search-urls.ts to centralize URLs:',
      'playwright.guide2.title': 'Create the Page Object (GoogleSearchPage.ts)',
      'playwright.guide2.desc': 'Create pages/GoogleSearchPage.ts with selectors and methods:',
      'playwright.guide3.title': 'Create the test file (google-search.spec.ts)',
      'playwright.guide3.desc': 'Create tests/google-search.spec.ts with test cases:',
      'playwright.guide4.title': 'Verify BasePage exists',
      'playwright.guide4.desc': 'Confirm that utils/base-page.ts is in the project (already included):',
      'playwright.guide5.title': 'Configure playwright.config.ts (optional)',
      'playwright.guide5.desc': 'If you want to run only on Chromium, verify the configuration:',
      'playwright.guide6.title': 'Run the specific test',
      'playwright.guide6.desc': 'Execute only the Google search test:',
      'playwright.guide7.title': 'Run with UI Mode',
      'playwright.guide7.desc': 'To debug the test visually step by step:',
      'playwright.guide8.title': 'View generated reports',
      'playwright.guide8.desc': 'Review the automatically generated HTML and Word reports:',
      
      // Tips
      'playwright.tips.title': 'Additional tips',
      'playwright.tips.selectors': 'Prioritize selectors by role, label or data-testid',
      'playwright.tips.waits': 'Playwright waits automatically, but use',
      'playwright.tips.waits.code': 'waitForSelector()',
      'playwright.tips.waits.when': 'when necessary',
      'playwright.tips.screenshots': 'Screenshots are captured automatically with the',
      'playwright.tips.screenshots.code': 'execute()',
      'playwright.tips.reports': 'Word reports are generated automatically in',
      'playwright.tips.reports.path': 'test-reports/',
      'playwright.tips.uimode': 'Use',
      'playwright.tips.uimode.code': '--ui',
      'playwright.tips.uimode.desc': 'for interactive visual debugging',
      
      // General labels
      'playwright.step': 'Step',
      'playwright.copy': 'Copy',
      'playwright.copied': 'Copied',
      
      // Selenium
      'selenium.title': 'Selenium',
      'selenium.subtitle': 'Professional web automation with Selenium WebDriver, Java and Cucumber BDD',
      'selenium.tab.github': 'Download from GitHub',
      'selenium.tab.guide': 'Usage Guide',
      'selenium.framework': 'Automation Framework',
      'selenium.preReq.title': 'Prerequisites',
      'selenium.preReq.java': 'Java JDK 11 or higher',
      'selenium.preReq.maven': 'Maven 3.6 or higher',
      'selenium.preReq.ide': 'IntelliJ IDEA (recommended) or any Java IDE',
      'selenium.preReq.chrome': 'Google Chrome (latest version)',
      
      // GitHub steps
      'selenium.step1.title': 'Clone the repository',
      'selenium.step1.desc': 'Open your terminal and run the following command to clone the project:',
      'selenium.step2.title': 'Verify prerequisites',
      'selenium.step2.desc': 'Make sure you have Java JDK 11+, Maven 3.6+ and Google Chrome installed:',
      'selenium.step3.title': 'Install project dependencies',
      'selenium.step3.desc': 'Install all Maven dependencies:',
      'selenium.step4.title': 'Verify project structure',
      'selenium.step4.desc': 'Confirm that the project has the following structure:',
      'selenium.step5.title': 'Configure WebDriver (optional)',
      'selenium.step5.desc': 'The project uses WebDriverManager for automatic driver management. If you need manual configuration, edit DriverManager.java:',
      'selenium.step6.title': 'Verify installation by running tests',
      'selenium.step6.desc': 'Execute all tests to confirm the framework works:',
      'selenium.step7.title': 'View generated HTML reports',
      'selenium.step7.desc': 'Open the automatically generated Cucumber HTML report:',
      'selenium.step8.title': 'Verify Word reports',
      'selenium.step8.desc': 'Word reports are automatically generated in the test-reports/ folder:',
      
      // Guide steps
      'selenium.guide.intro.title': 'Create a new Google search test',
      'selenium.guide.intro.desc': 'This guide will show you how to create a complete test to search for the word "Automation" on Google using the Page Object Model pattern with Selenium WebDriver, Java and Cucumber.',
      'selenium.guide1.title': 'Create the constants file',
      'selenium.guide1.desc': 'Create src/main/java/com/selenium/constants/SearchUrls.java:',
      'selenium.guide2.title': 'Create the Page Object (GoogleSearchPage.java)',
      'selenium.guide2.desc': 'Create src/main/java/com/selenium/pages/GoogleSearchPage.java:',
      'selenium.guide3.title': 'Create the Feature file (google-search.feature)',
      'selenium.guide3.desc': 'Create src/test/resources/features/google-search.feature:',
      'selenium.guide4.title': 'Create Step Definitions (GoogleSearchSteps.java)',
      'selenium.guide4.desc': 'Create src/test/java/com/selenium/stepdefinitions/GoogleSearchSteps.java:',
      'selenium.guide5.title': 'Verify Hooks.java exists',
      'selenium.guide5.desc': 'Confirm that src/test/java/com/selenium/hooks/Hooks.java manages the lifecycle:',
      'selenium.guide6.title': 'Update TestRunner.java',
      'selenium.guide6.desc': 'Verify that src/test/java/com/selenium/runners/TestRunner.java includes the new feature:',
      'selenium.guide7.title': 'Run the specific test',
      'selenium.guide7.desc': 'Execute only Google search tests using tags:',
      'selenium.guide8.title': 'View generated reports',
      'selenium.guide8.desc': 'Review the automatically generated HTML and Word reports:',
      
      // Tips
      'selenium.tips.title': 'Additional tips',
      'selenium.tips.selectors': 'Prioritize id > name > className > xpath for better stability',
      'selenium.tips.waits': 'Use',
      'selenium.tips.waits.code1': 'WebDriverWait',
      'selenium.tips.waits.with': 'with',
      'selenium.tips.waits.code2': 'ExpectedConditions',
      'selenium.tips.pagefactory': 'Use',
      'selenium.tips.pagefactory.code': '@FindBy',
      'selenium.tips.pagefactory.desc': 'annotations to initialize elements',
      'selenium.tips.tags': 'Organize tests with @smoke, @regression, @negative for selective execution',
      'selenium.tips.screenshots': 'Automatic screenshots with the',
      'selenium.tips.screenshots.code': 'execute()',
      'selenium.tips.screenshots.desc': 'method from BasePage',
      
      // General labels
      'selenium.step': 'Step',
      'selenium.copy': 'Copy',
      'selenium.copied': 'Copied',
    },
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
